crm_project/crm_app/urls.py
from django.urls import path,include
from crm_app import views


app_name = 'crm_app'



urlpatterns = [
    # customer account section
    # path('login/', views.login, name='login'),
    path('',views.staff_login,name="staff_login"),
    path('index/', views.index, name='index'),
    path('logout/',views.logout,name="logout"),
    # path('register/', views.register, name='register'),
    # ADMIN REGISTER
    path('**admin-register**/', views.admin_register, name='admin_register'),
    # SUPERVISOR AND STAFF  REGISTER
    path('**staff-register**/',views.register,name="staff_register"),
    # path('**sitestaff-register**/', views.sitestaff_register, name='sitestaff_register'),
    # staff account section
    # path('staff-login/',views.staff_login,name="staff_login"),
    # path('register/', views.register, name='register'),
    path('starter/', views.starter, name='starter'),
    path('customers/', views.customer, name='customers'),
    path('customer-edit/<int:cust_id>/', views.customer_update, name='customer_update'),
    path('add-customer/', views.add_customer, name='add_customer'),
    path('customer-delete/<int:cust_id>/', views.customer_delete, name='customer_delete'),
    path('customer-search-result', views.customer_search, name='customer_search'),
    
    path('leads/', views.leads, name='leads'),
    path('add-leads/', views.add_leads, name='add_leads'),
    path('leads-update/<int:item_id>', views.lead_update, name='leads_edit'),
    path('leads-delete/<int:item_id>', views.lead_delete, name='leads_delete'),
    path('junk-leads/', views.pending_leads, name='junk_leads'),
    path('junk-leads-search-result/', views.pending_lead_search, name='junk_lead_search'),
    path('open-leads/', views.open_leads, name='open_leads'),
    path('closed-leads/', views.closed_leads, name='closed_leads'),
    path('lead-search/', views.lead_search, name='lead_search'),
    path('lead-search-result/', views.lead_search_admin, name='lead_search_admin'),
    path('customer-profile/<int:customer_id>', views.customer_profile, name='customer_profile'),
    path('quotation-invoice/', views.Quotation_invoice, name='quotation_invoice'),
    path('products/', views.products, name='products'),
    path('search-result/', views.search, name='search'),
    path('cart/', views.cart, name='addcart'),
    path('cart-empty/', views.cart2, name='cart2'),
    path('add-cart/<int:product_id>/',views.add_cart,name="add_cart"),
    path('cartDetails/<int:product_id>/',views.buy_now,name="cartDetails"),
    path('min_product/<int:product_id>/',views.minus_button,name="minus"),
    path('del-product/<int:product_id>/',views.delete_button,name="del_product"),
    path('invoice-pdf/<int:customer_id>',views.invoice_pdf,name="invoice_pdf"),
    path('open-lead-search-result',views.open_lead_search,name="open_lead_search"),
    path('closed-lead-search-result',views.closed_lead_search,name="closed_lead_search"),
    path('quotation-invoice-buy/<int:customer_id>/',views.Quotation_invoice_buy,name="Quotation_invoice_buy"),
    path('project-management',views.project_management,name="project_management"),
    path('tools-management',views.tools_management,name="tools_management"),
    path('project-management-update/<int:item_id>/',views.ProjectManagementUpdate,name="project_management_update"),
    path('product-new',views.product_new,name="product_new"),
    path('tools-management-update/<int:item_id>/',views.tools_management_update,name="tools_management_update"),
    path('task/', views.task, name='task'),
    path('add-task/', views.add_task, name='add_task'),
    path('edit-task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('delete-task/<int:task_id>/', views.delete_task, name='delete_task'),
    
    
 

    # PRODUCTS SECTION
    path('cctv/',views.cctv,name="cctv"),
    path('video-door-phone/',views.video_door_phone,name="video_door_phone"),
    path('projector/',views.projector,name="projector"),

    



]

crm_project/crm_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm_app.urls')),
    path('', include('tools_management_app.urls')),
    # path('', include('tools_management.urls')),

    
    
    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

crm_project/templates/admin-register.html
{% load static %}
<!doctype html>
<html lang="en">

    
<!-- Mirrored from preview.pichforest.com/dashonic/layouts/auth-signin-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 26 Mar 2022 07:08:57 GMT -->
<head>
        
        <meta charset="utf-8" />
        <title>Admin Register</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Pichforest" name="author" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'assets/images/atlas-logo-small.png' %}">

        <!-- Bootstrap Css -->
        <link href="{% static 'assets2/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'assets2/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'assets2/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

    </head>

    
    <body>

    <!-- <body data-layout="horizontal"> -->

        <div class="authentication-bg min-vh-100">
            <div class="bg-overlay bg-white"></div>
            <div class="container">
                <div class="d-flex flex-column min-vh-100 px-3 pt-4">
                    <div class="row justify-content-center my-auto">
                        <div class="col-md-8 col-lg-6 col-xl-4">
                            
                            <div class="text-center  py-5">
                                <div class="mb-4 mb-md-5">
                                    <a class="d-block auth-logo">
                                        <img src="{% static 'assets/images/atlas-logo.png' %}" alt="" height="35" class="auth-logo-dark">
                                        {% comment %} <img src="{% static 'assets/images/atlas-logo.png' %}" alt="" height="22" class="auth-logo-light"> {% endcomment %}
                                    </a>
                                </div>
                                <div class="mb-4">
                                    <h5>Welcome Back !</h5>
                                    <p>Sign up to continue to Atlas Kitchen.</p>
                                </div>
                                <div>
                                    {% for message in messages %}
                                    <h4 style='color:red; font-size:15px; font-weight:300'>{{message}}</h4>
                                    {% endfor %}
                                </div>
                                <form method='post'>
                                    {% csrf_token %}
                                    <div class="form-floating form-floating-custom mb-3">
                                        <input type="text" class="form-control" name="username" id="username" placeholder="Employee ID">
                                        <label for="input-username">Username</label>
                                        <div class="form-floating-icon">
                                            <i class="uil uil-users-alt"></i>
                                        </div>
                                    </div>
                                    <div class="form-floating form-floating-custom mb-3">
                                        <input type="email" class="form-control" name="email" id="username" placeholder="Employee ID">
                                        <label for="input-username">Email</label>
                                        <div class="form-floating-icon">
                                            <i class="uil uil-users-alt"></i>
                                        </div>
                                    </div>
                                   
                                    <div class="form-floating form-floating-custom mb-3">
                                        <input type="password" class="form-control" name="password1" id="password" placeholder="Enter Password">
                                        <label for="input-password">Password</label>
                                        <div class="form-floating-icon">
                                            <i class="uil uil-padlock"></i>
                                        </div>
                                    </div>
                                    <div class="form-floating form-floating-custom mb-3">
                                        <input type="password" class="form-control" name="password2" id="password" placeholder="Enter Password">
                                        <label for="input-password">Confirm Password</label>
                                        <div class="form-floating-icon">
                                            <i class="uil uil-padlock"></i>
                                        </div>
                                    </div>
                                    
                                    <div class="mt-3">
                                        <button class="btn btn-info w-100" id="btn1" type="submit">Register</button>
                                    </div>

                                    {% comment %} <div class="mt-4">
                                        <a href="auth-resetpassword-basic.html" class="text-muted text-decoration-underline">Forgot your password?</a>
                                    </div> {% endcomment %}
                                </form><!-- end form -->

                                <div class="mt-5 text-center text-muted">
                                    <p>Alreday Have An Account? <a href="{% url 'crm_app:staff_login' %}" class="fw-medium text-decoration-underline"> Login </a></p>
                                </div>
                            </div>
                        </div><!-- end col -->
                    </div><!-- end row -->

                    <div class="row">
                        <div class="col-xl-12">
                            <div class="text-center text-muted p-4">
                                <p class="mb-0">&copy; <script>document.write(new Date().getFullYear())</script> A2Z ALPHABET SOLUTIONZ 
                            </div>
                        </div><!-- end col -->
                    </div><!-- end row -->

                </div>
            </div><!-- end container -->
        </div>
        <!-- end authentication section -->

        <!-- JAVASCRIPT -->
        {% comment %} <script>
            $("#btn1").click(function(e){
                e.preventDefault();
                var username = $('#username').val()
                var password = $('#password').val()
                var data ={
                    'csrfmiddlewaretoken':'{{csrf_token}}',
                    'username':username,
                    'password':password
                    
                }
                if(username == ''){
                    alert('Enter valid username')
                }else if(password == ''){
                    alert('Enter valid Password')
                }else
                {
                $.ajax({
                    url:'/',
                    method:"POST",
                    data :data,
                    dataType:'json',
                    success:function(data){
                        if(data.success){
                            alert('User Logged in')
                            window.location.replace('/index/')
                        }else{
                            alert('User is not authenticated')
                        }
                    }
                })
            }
    
            })
        </script>

 {% endcomment %}


        <script src="{% static 'assets2/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets2/libs/metismenujs/metismenujs.min.js' %}"></script>
        <script src="{% static 'assets2/libs/simplebar/simplebar.min.js' %}"></script>
        <script src="{% static 'assets2/libs/feather-icons/feather.min.js' %}"></script>

    </body>

<!-- Mirrored from preview.pichforest.com/dashonic/layouts/auth-signin-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 26 Mar 2022 07:08:57 GMT -->
</html>

crm_project/templates/sitestaff-register.html
{% load static %}
<!doctype html>
<html lang="en">

    
<!-- Mirrored from preview.pichforest.com/samply/layouts/auth-register.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 01 Dec 2021 12:27:17 GMT -->
<head>
        <meta charset="utf-8" />
        <title>SiteStaff Regsiter</title>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Pichforest" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'assets/images/atlas-logo-small.png' %}">

        <!-- Bootstrap Css -->
        <link href="{% static 'assets/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'assets/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />
        <!-- Dark Mode Css-->
        <link href="{% static 'assets/css/dark-layout.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

    </head>

    <body data-sidebar="dark">

    <!-- <body data-layout="horizontal" data-topbar="dark"> -->
        <div class="account-pages my-5 pt-sm-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-10">
                        <div class="text-center mb-5">
                            <a href="index.html" class="auth-logo">
                                <img src="{% static 'assets/images/atlas-logo.png' %}" alt="Logo Dark" height="28" class="auth-logo-dark">
                                <img src="{% static 'assets/images/atlas-logo.png' %}" alt="Logo Light" height="28" class="auth-logo-light">
                            </a>
                            <p class="font-size-15 text-muted mt-3"></p>
                        </div>
                        <div class="card overflow-hidden">
                            <div class="row g-0">
                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4">

                                        <div>
                                            <h5>SiteStaff Register</h5>
                                            <p class="text-muted"></p>
                                        </div>
                                        <div>
                                            {% for message in messages %}
                                            <h4 style='color:red; font-size:15px; font-weight:300'>{{message}}</h4>
                                            {% endfor %}
                                        </div>
                                        <div class="mt-4 pt-3">
                                            <form  method="post">
                                                {% csrf_token %}
                                                    <div class="form-group">
                                                        <label for="recipient-name1" class="col-form-label">Username</label>
                                                        <input type="text" class="form-control" placeholder=" " name="username" id="username" required="">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="recipient-email" class="col-form-label">Email</label>
                                                        <input type="email" class="form-control" placeholder=" " name="email" id="email" required="">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="password1" class="col-form-label">Password</label>
                                                        <input type="password" class="form-control" placeholder=" " name="password1" id="password1" required="">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="password2" class="col-form-label">Confirm Password</label>
                                                        <input type="password" class="form-control" placeholder=" " name="password2" id="password2" required="">
                                                    </div>
                                                    <div class="right-w3l">
                                                        <input type="submit" id="btn1" class="btn btn-info" value='Register'>
                                                    </div>
                                                </form>
                                        </div>
                    
                                    </div>
                                </div>
                                {% comment %} <div class="col-lg-6">
                                    <div class="p-lg-5 p-4 bg-auth h-100 d-none d-lg-block">
                                        <div class="bg-overlay"></div>
                                        
                                    </div>
                                </div> {% endcomment %}
                                
                            </div>
                        </div>
                        <!-- end card -->
                        <div class="mt-5 text-center">
                            <p>Already have an account ? <a href="{% url 'crm_app:staff_login' %}" class="fw-semibold text-decoration-underline"> Login </a> </p>
                            {% comment %} <p>© <script>document.write(new Date().getFullYear())</script> <b>Samply</b>. Crafted with <i class="mdi mdi-heart text-danger"></i> by Pichforest</p> {% endcomment %}
                        </div>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end account page -->

        <!-- JAVASCRIPT -->
        {% comment %} <script>
            $('#btn1').click(function(e){
                e.preventDefault();
                var username = $('#username').val()
                var email = $('#email').val()
                var password1 = $('#password1').val()
                var password2 = $('#password2').val()
                var data ={
                    'csrfmiddlewaretoken':'{{csrf_token}}',
                    'username':username,
                    'email':email,
                    'password1':password1,
                    'password2':password2,
    
                    
                }
                if(username == ''){
                    alert('Enter Valid Username')
                }else if(email ==''){
                    alert('Enter Valid Email')
                }else if(password1 ==''){
                    alert('Enter Valid Password')
                }else if(password2 ==''){
                    alert('Enter Valid Password')
                }else
                {
                $.ajax({
                    url:'register/',
                    method:"POST",
                    data :data,
                    dataType:'json',
                    success:function(data){
                        if(data.success){
                            alert('Succesfully Registered')
                            window.location.replace('login')
                        }else{
                            alert('User is not authenticated')
                        }
                    }
                })
            }
            })
        </script> {% endcomment %}
        <script src="{% static 'assets/libs/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'assets/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets/libs/metismenu/metisMenu.min.js' %}"></script>
        <script src="{% static 'assets/libs/simplebar/simplebar.min.js' %}"></script>
        <script src="{% static 'assets/libs/node-waves/waves.min.js' %}"></script>

        <script src="{% static 'assets/js/app.js' %}"></script>

    </body>

<!-- Mirrored from preview.pichforest.com/samply/layouts/auth-register.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 01 Dec 2021 12:27:17 GMT -->
</html>

crm_project/templates/staff_login.html
{% load static %}
<!doctype html>
<html lang="en">

    
<!-- Mirrored from preview.pichforest.com/dashonic/layouts/auth-signin-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 26 Mar 2022 07:08:57 GMT -->
<head>
        
        <meta charset="utf-8" />
        <title>Sign In</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Pichforest" name="author" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'assets/images/atlas-logo-small.png' %}">

        <!-- Bootstrap Css -->
        <link href="{% static 'assets2/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'assets2/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'assets2/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

    </head>

    
    <body>

    <!-- <body data-layout="horizontal"> -->

        <div class="authentication-bg min-vh-100">
            <div class="bg-overlay bg-white"></div>
            <div class="container">
                <div class="d-flex flex-column min-vh-100 px-3 pt-4">
                    <div class="row justify-content-center my-auto">
                        <div class="col-md-8 col-lg-6 col-xl-4">
                            
                            <div class="text-center  py-5">
                                <div class="mb-4 mb-md-5">
                                    <a class="d-block auth-logo">
                                        <img src="{% static 'assets/images/atlas-logo.png' %}" alt="" height="35" class="auth-logo-dark">
                                        {% comment %} <img src="{% static 'assets/images/atlas-logo.png' %}" alt="" height="22" class="auth-logo-light"> {% endcomment %}
                                    </a>
                                </div>
                                <div class="mb-4">
                                    <h5>Welcome Back !</h5>
                                    <p>Sign in to continue to Atlas Kitchen.</p>
                                </div>
                                <form method='post'>
                                    {% csrf_token %}
                                    <div class="form-floating form-floating-custom mb-3">
                                        <input type="text" class="form-control" name="username" id="username" placeholder="Employee ID">
                                        <label for="input-username">Employee ID</label>
                                        <div class="form-floating-icon">
                                            <i class="uil uil-users-alt"></i>
                                        </div>
                                    </div>
                                    <div class="form-floating form-floating-custom mb-3">
                                        <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
                                        <label for="input-password">Password</label>
                                        <div class="form-floating-icon">
                                            <i class="uil uil-padlock"></i>
                                        </div>
                                    </div>
                                    <div class="mt-3">
                                        <button class="btn btn-info w-100" id="btn1" type="submit">Log In</button>
                                    </div>

                                    {% comment %} <div class="mt-4">
                                        <a href="auth-resetpassword-basic.html" class="text-muted text-decoration-underline">Forgot your password?</a>
                                    </div> {% endcomment %}
                                </form><!-- end form -->

                                <div class="mt-5 text-center text-muted">
                                    <p>Don't have an account ? <a href="{% url 'crm_app:staff_register' %}" class="fw-medium text-decoration-underline"> Signup </a></p>
                                </div>
                            </div>
                        </div><!-- end col -->
                    </div><!-- end row -->

                    <div class="row">
                        <div class="col-xl-12">
                            <div class="text-center text-muted p-4">
                                <p class="mb-0">&copy; <script>document.write(new Date().getFullYear())</script> A2Z ALPHABET SOLUTIONZ 
                            </div>
                        </div><!-- end col -->
                    </div><!-- end row -->

                </div>
            </div><!-- end container -->
        </div>
        <!-- end authentication section -->

        <!-- JAVASCRIPT -->
        <script>
            $("#btn1").click(function(e){
                e.preventDefault();
                var username = $('#username').val()
                var password = $('#password').val()
                var data ={
                    'csrfmiddlewaretoken':'{{csrf_token}}',
                    'username':username,
                    'password':password
                    
                }
                if(username == ''){
                    alert('Enter valid username')
                }else if(password == ''){
                    alert('Enter valid Password')
                }else
                {
                $.ajax({
                    url:'/',
                    method:"POST",
                    data :data,
                    dataType:'json',
                    success:function(data){
                        if(data.success){
                            alert('User Logged in')
                            window.location.replace('/index/')
                        }else{
                            alert('User is not authenticated')
                        }
                    }
                })
            }
    
            })
        </script>




        <script src="{% static 'assets2/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets2/libs/metismenujs/metismenujs.min.js' %}"></script>
        <script src="{% static 'assets2/libs/simplebar/simplebar.min.js' %}"></script>
        <script src="{% static 'assets2/libs/feather-icons/feather.min.js' %}"></script>

    </body>

<!-- Mirrored from preview.pichforest.com/dashonic/layouts/auth-signin-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 26 Mar 2022 07:08:57 GMT -->
</html>